-- =============================================================================
-- RouteFlow — PostgreSQL Row-Level Security (Phase 5.2) — SUPERSEDED, DO NOT EDIT
--
-- The policy DDL that used to live here now lives in
--   apps/api/prisma/migrations/20260909000000_rls/migration.sql
-- which is the ONLY authoritative copy: it is what `prisma migrate deploy`
-- runs, what scripts/rls-preflight.mjs parses the policied-table list out of,
-- and what carries the post-apply assertion that RLS really ended up enabled
-- (the policy loop swallows its own per-table errors, so a 0 exit alone proves
-- nothing).
--
-- Do NOT re-add the policy DDL here. A second copy of the table list is exactly
-- how a table gets armed in production without the pre-flight ever counting its
-- NULL-"tenantId" rows — and once FORCE ROW LEVEL SECURITY is on, such a row is
-- invisible and unwritable to every role, including the app's own connection.
--
-- Apply (prod):  railway run --service postgres node apps/api/scripts/prod-migrate.mjs
-- Apply (local): npx prisma migrate dev   (docker-compose Postgres)
-- =============================================================================
