-- RF-014: Enforce unique (tenantId, orderNumber) per tenant to prevent
-- duplicate order numbers generated by concurrent MAX+1 reads.
-- The WHERE clause excludes NULL orderNumbers (drafts without a number).
-- MIGRATION REQUIRED — DO NOT AUTO-APPLY; run manually against Railway prod.

CREATE UNIQUE INDEX IF NOT EXISTS "Order_tenantId_orderNumber_key"
  ON "Order"("tenantId","orderNumber")
  WHERE "orderNumber" IS NOT NULL;
