-- The per-product costing label defaulted to FIFO, but no write path has ever
-- computed FIFO: every receipt maintains Product.averageCost via nextAverageCost
-- regardless of the label, and the only lot-consumption code (recordSale) has had
-- no caller since c5f579c2 removed the /orders/:id/complete route. Valuation now
-- reads the weighted average for every method, so the label no longer changes any
-- number — this makes the stored default state what the system actually does.
--
-- Only the column DEFAULT changes here. Existing rows are deliberately left alone:
-- relabelling live products is a tenant-data edit, handled separately by a
-- dry-run-first script so it can be reviewed per tenant.
ALTER TABLE "Product" ALTER COLUMN "costingMethod" SET DEFAULT 'AVCO';
